name: Deploy PubSub + Kafka + RabbiMQ with Terraform and Ansible
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev, prod)"
        required: true
        default: dev

permissions:
  contents: read
  id-token: write

jobs:
  deploy-function:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - run: |
          gcloud functions deploy process_csv_to_pubsub \
            --runtime python310 \
            --trigger-resource dev-pubsub-focus-infusion-463923-t8-my-bucket-7828 \
            --trigger-event google.storage.object.finalize \
            --entry-point process_csv_to_pubsub \
            --region us-east1 \
            --source functions/
